# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '380160487772.dkr.ecr.ap-southeast-1.amazonaws.com/test'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      AWS.AccessKeyID: $(AWS_ACCESS_KEY_ID)
      AWS.SecretAccessKey: $(AWS_SECRET_ACCESS_KEY)
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: $(tag)
    - task: ECRPushImage@1
      displayName: Push Image
      inputs:
        regionName: 'ap-southeast-1'
        sourceImageName: $(tag)
        repositoryName: $(tag)
    