version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t hello-world:latest .
      - docker tag hello-world:latest 380160487772.dkr.ecr.ap-southeast-1.amazonaws.com/hello-world:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 380160487772.dkr.ecr.ap-southeast-1.amazonaws.com/hello-world:latest
